alexandresanlim/Badges4-README.md-Profile

README.md

Fixed following links
- LinkedIn
- Twitter
- YouTube
- Spotify
Changed a typo: "Outhers" → "Others"

🛠 Fixed links of some Social Media Icons

---

README.md

Update:
> unity badge added in skill section.
> patreon badge added in funding section.
> itch.io badge added in game section.
> audacity badge added in sound section.
> github badge added in social section.

5 more badges addition

---

README.md

Added badge for gitlab

---

README.md

Some URLs had a quote after them which was not good to copy. So I removed them

Removed some unnecessary quotes after the URL

---

README.md

Fixed typo and color

---

README.md

In my opinion calling it Uri is wrong and even on [Shields.io](https://shields.io/) website it's called URL, not Uri so that's why I made this PR.

Change Uri to URL

---

README.md

Added a couple of new badges in the Skills section and removed a duplicate Go badge.

Added Raspberry Pi, Conda, Kubernetes and other badges

---

README.md

Added new badges for devs, following the tutorial on: [How To Make Custom Language Badges for your Profile using shields.io
](https://javascript.plainenglish.io/how-to-make-custom-language-badges-for-your-profile-using-shields-io-d2aeaf016b6b)
--

New badges: Unreal engine and wearos #1

---

README.md

Xcode is an IDE for macOS. I've added the Xcode badge right about Visual Studio Code

Added Xcode badge

---

README.md

Added a badge for Jekyll to README.md and also fixed firebase badge link in table (it was not showing the logo)

Add badge for Jekyll to README.md

---

README.md

Add Ember.js Badge

---

README.md

Hi, I'd to contribute add the cypress badge.

add cypress badge

---

README.md

Added a badge for mariaDB in the database section

added mariaDB Badge

---

README.md

Added the Github sponsor badge

Add Github sponsor badge

---

README.md

Added Stack Exchange in Social. Also, earlier the color of the badge of XDA-Developer was different from the original, so changed it to perfection😀.

Added StackExchange in Social & Change in the badge of XDA-Developer

---

README.md

Added MATERIALIZE-CSS badge

---

README.md

node.js, .net, vue.js, ember.js, nuxt.js, next.js, chart.js, itch.io and dev.to logos updated

Updated logos

---

README.md

Removed extra Python badge

---

README.md

@alexandresanlim  Kindly review PR

Update for Research Gate Badge

---

README.md

Hello my friend ,
I added a new set of badge icons that includes the following.
- new python
- RabbitMQ
- new Django
- Django Rest
- FastApi
- PyCharm
- PhpStorm
Thanks for adding.
_With respect_

added new badge icons , RabbitMq , PhpStorm , FastApi , . . .

---

README.md

Badge for [Neo4j Graph Databases](https://neo4j.com/)

Add Neo4j Badge to Databases

---

README.md

[Building Mobile Applications with Apache Cordova](https://cordova.apache.org/)

Add badge for Apache Cordova in Mobile Frameworks

---

README.md

currently Added Web Browsers menu and 7 badges of browsers and in future i will add more menus and badages

Added Web Browsers menu and 7 badges of browsers

---

README.md

Kaggle icon added by @waqarg2001

Kaggle icon added

---

README.md

[GitBook](https://www.gitbook.com/) helps publish documentation

add GitBook to Frameworks

---

README.md

Changed the text color of the Oracle icon so as to make it more visible

Added a few more Icons.

---

README.md

By this badge, you can show the adobe apps all in one except showing every apps

Added Adobe Creative Cloud

---

README.md

Added web-app hosting platforms as mentioned in this issue #86

add web-app hosting platforms

---

README.md

add fastify  and supabase. and fastify below express js because both node js based framework

add fastify and supabase

---

README.md

Added badges for:
1. NumPy
2. Pandas
3. Plotly

Added extra badges.

---

README.md

* Add Cocoapods badge in the frameworks category;
* Add Travis CI badge in the Cloud category.

Add Cocoapods and Travis CI badges

---

README.md

The parameter to show the icons of vue.js and ember.js it was wrong.

bug:Update of the names of the icons of vue.js and ember.js

---

README.md

- Add LaTeX badge in the languages category.

Add LaTex badge

---

README.md

Fixed .NET, Chart.js, Node.js, dev.to, itch.io, Replit and Travis CI Badges
Added CircleCI, LineageOS, Manjaro, Cirrus CI and Drone CI Badges

Add and fix some badges

---

README.md

OpenGL badge added in Framework section

add OpenGL

---

README.md

- Add Notion badge in the Office category.

Add Notion badge

---

README.md

I have added Streamlit for which i had created an isssue earlier #116 . If you need some more information please let me know.
Here's the screenshot of the addition as well.

Added Streamlit badge

---

README.md

added Amazon DynamoDB icon in Database
and Swiggy in Food

added Amazon DynamoDB icon in Database and Swiggy in Food

---

README.md

- Add Trello badge in the Office category.

Add Trello badge

---

README.md

Added Badges for PyTorch and PyTorch Ligtning!

Added PyTorch and PyTorch Lightning

---

README.md

Sololearn - https://www.sololearn.com

Added Sololearn badge

---

README.md

* Added LeetCode
* Added Codechef
* Added Cockroach Labs

Made 3 New Additions

---

README.md

Added the following badges - 
* Amazon Prime(Streaming)
* Premiere Pro(Design)
* Lightroom(Design)
* Airtable(Office)

Made New Additions

---

README.md

Hey there! I really liked your Badges 4 README Profile project. It's helpful and amazing :)
I added some badges which are listed below -
- Haskell (Languages)
- Realm (Database)
- Hulu (Streaming)
- KFC (Food)
- Zomato (Food)

Added 5 new badges

---

README.md

Added 3 badges-
1) Linktree (socials)
2) Myanimelist (socials)
3) Foodpanda  (food)
and contributor to the repository.

Added 3 badges.

---

README.md

Add Codesandbox and macOS

---

README.md

Added DeviantArt to socials
Added Wechat to contacts.

Added DeviantArt and Wechat

---

README.md

I added Airflow's badge to category frameworks. Because I don't know if it is allowed to create a new category, it seems to me that it is the category that more fits.

Adding Apache Airflow

---

README.md

Added Jira.

---

README.md

Added RStudio

---

README.md

Added **Storybook** badge following the official logo color.
Solves #161

Added Storybook badge

---

README.md

uploaded badges In design section and changed the color scheme of sketch

uploaded more badges

---

README.md

Here's an example of the badge that was added in this PR 👇

Added Vercel badge

---

README.md

Related issue: #166 
- Added ESLint badge: ![eslint](https://img.shields.io/badge/eslint-3A33D1?style=for-the-badge&logo=eslint&logoColor=white)
- Created a new section called **Linters**, with 🧐 emoji

Added ESLint badge

---

README.md

- Added **Alacritty** badge
- Created a new **💻 Terminal** section for it

Added Alacritty badge into a new Terminal section

---

README.md

Added **Tmux** badge in the **Terminal** section.

Added Tmux badge

---

README.md

i added both badges under frameworks section

added Socket.io badge and Apollo GraphQL badge

---

README.md

added this badge
- <img src="https://img.shields.io/badge/Goodreads-372213?style=for-the-badge&logo=goodreads&logoColor=white"></img>

added goodreads badge

---

README.md

#184 
Hii, I have added expo-cli right under the react badge in frameworks section. Let me know if any chances needs to be made. Thanks!

added expo-cli inside frameworks

---

README.md

Litecoin and Ethereum color scheme fixed & added Bitcoin Cash, Bitcoin Sv and Stellar

fixed color scheme & added more cryptocurrency

---

README.md

duplicate items were removed from cryptocurrency

duplicate badge should  were removed

---

README.md

Added polywork badge under social

Added polywork

---

README.md

Add Erlang

---

README.md

Add Amazon DynamoDB

---

README.md

Changed `Deno.JS` to `Deno`

---

README.md

Add 3 new badges

---

README.md

Added Godot under Frameworks as https://img.shields.io/badge/Godot-478CBF?style=for-the-badge&logo=GodotEngine&logoColor=white

Added Godot Icon

---

README.md

Added 4 New Badges

---

README.md

- TeamSpeak
- Open Office
- Appel silicon (m1 / darwin)
- Huawei
- Battle.net
- Origin
- Riot
- Exercism
- oh-my-zsh (zsh)
- iTerm2
- Hyper

Added 11 new badges

---

README.md

Add 10 new badges, including:
- ![](https://img.shields.io/badge/Hexo-0E83CD?style=for-the-badge&logo=hexo&logoColor=white) ![](https://img.shields.io/badge/Webpack-8DD6F9?style=for-the-badge&logo=Webpack&logoColor=white) ![](https://img.shields.io/badge/Apache-D22128?style=for-the-badge&logo=Apache&logoColor=white) ![](https://img.shields.io/badge/Istio-466BB0?style=for-the-badge&logo=Istio&logoColor=white) ![](https://img.shields.io/badge/JWT-000000?style=for-the-badge&logo=JSON%20web%20tokens&logoColor=white) under **🚀 Frameworks**
- ![](https://img.shields.io/badge/Joplin-1071D3?style=for-the-badge&logo=joplin&logoColor=white) under **👨‍💻 Office**
- ![](https://img.shields.io/badge/Alibaba_Cloud-FF6A00?style=for-the-badge&logo=alibabacloud&logoColor=white) under **☁ Cloud**
- …

Add 10 new badges

---

README.md

Add Tableau

---

README.md

This is my code to **Social** category
> Profile Visitors
```
```
> Codeforces
```
```

Add two new badge named Profile Visitors & Codeforces

---

README.md

Hii, I have added 'HASURA' under frameworks sections. Let me know if any chances are required in this PR. Cheers

added hasura

---

README.md

- I can't find any group about **ORM** that's why I created a new group named ORM - Object Relational Mapping
- Secondly add a new badge named **Sequelize** to this.

Add new group ORM and add new badge to this named Sequelize

---

README.md

- Add a new ORM tools named **Prisma** to ORM Section.

Add prisma badge to ORM section

---

README.md

Hibernate Badge added to ORM Section

Hibernate Badge added to ORM Section

---

README.md

I have just added the Scratch Badge in the languages section.

Added Scratch Badge

---

README.md

tether, binance and polkadot were added and managed alphabetical order crypto section

added cryptocoins

---

README.md

I have added **Scratch** to languages. My Readme.md is updated. Pls merge these files and add scratch to them. 
I will be grateful to join as  a Contributor 
Thank You
- SparkScratch-P ([https://sparkscratch-p.github.io/](https://sparkscratch-p.github.io/))

Added 'Scratch' in Languages

---

README.md

- Add a new section named `ETL` under `ORM`
- Add 3 new badge of ETL 
- Databricks
- Talend
- Spark Ar

Add ETL Section & some badge on that section

---

README.md

updated cryptocurrency section

---

README.md

Blog, Contact and Cloud sections are arranged in alphabetical manner

Arranged in alphabetical order

---

README.md

- Fix previous `Cloud` section issue.
- Sort `Database` section in Alphabetical Order

Update Cloud & sort Database section in Alphabetical order

---

README.md

- Sorting 4 badges section with `Alphabetical` order.
- Update `How to contribute` section for developer's to commit badge with `Alphabetical` order.

Sort 4 Section with Alphabetical order & update How to contribute

---

README.md

PHP Composer package repository

Add Packagist

---

README.md

Add Composer

---

README.md

Icq-new badge color fixed and added back gmail badge

badge color fixed

---

README.md

Hi! I haven't found a Git badge, so I put one in the Terminal section. Hope you like it! Thanks.

Added git badge

---

README.md

EditorConfig badge added in IDE plugin slot

Added new slot IDE plugins `new-badge`

---

README.md

`Material UI` badge fixed and `Materialize CSS ` badge removed due to no official or unofficial logo provided

Badge fixed in Framework slot `enhancement`

---

README.md

- As usual we sort all section with Alphabetical Order. This time I sorted `Social` section.

Sort Social Section

---

README.md

`Rollup.js` `Web3.js` `D3.js` `CodeceptJS` `Cytoscape.js` and `Reveal.js` are added in Frameworks slot

Badges added in Frameworks slot `new-badge`

---

README.md

Prezi is an online presentation tool.

Added "Prezi" badge in "Office" category

---

README.md

Reverts alexandresanlim/Badges4-README.md-Profile#323

Revert "Added Samsung laptop badge and databricks URL fixed"

---

README.md

SymfonyConnect is the social network and identity service for the Symfony community.

Added Symfony Connect

---

README.md

`Backbone Js`, `Interact Js` and `UnderScore Js` are added

Some badges are added and fixed in different slots

---

README.md

fixing some spaces and sorting the OS category in alphabetical order

visual changes

---

README.md

- Sorting `Store` section in Alphabetical order.

Sort Store Section

---

README.md

- Forgot to make a note for the Contributors about `List Updating` every month.

Make an Note for Contributors

---

README.md

`Adonis Js` added in Frameworks slot

---

README.md

- Create an individual Heading for `static` badge section.

Create Static Heading & Navigation

---

README.md

- Create 4 section for all  dynamic badges `individually`

Create individual section for Dynamic badges

---

README.md

- Change Options Name of `More` to `Creators`

Change Option Name More to Creators

---

README.md

Nem badge to add - Fifa

---

README.md

🏆 Add dynamically generated GitHub Stat Trophies on your readme
https://github.com/ryo-ma/github-profile-trophy

Add Trophy Stats

---

README.md

Adding a new Open Source named [Web Badge](https://github.com/mrhrifat/web-badge) to See More Repository Section.

Adding a new Open Source

---

README.md

Added Robot Framework:
https://img.shields.io/badge/Robot%20Framework-000000?style=for-the-badge&logo=robot-framework&logoColor=white

Submitted Robot Framework badge

---

README.md

add joomla CMS under Blog

---

README.md

Feature to track hits on github a repo

Add Hit Counter Badge in Dynamic Stats

---

README.md

- Someone add Profile Hits Counter badge to Dynamic section. Although I review & request for changes to rearrange badge. He make change but it was still not right. So I decided to rearrange that badge.

Fix Hits Counter Order

---

.github/FUNDING.yml

- Adding a link for support the `Collaborator`.

Refactor sponsor collaborator

---

README.md

- After notice, I correct some mistakes.

Fix some mistake

---

README.md

- Added `2` individual sponsor badge to support `Author` & `Collaborator`

Feat sponsor badge at profile

---

README.md

Added bio.link to social badges

Added BIO.LINK to the list

---

README.md

Added GroupMe in Contact icons

Added GroupMe in Contact icons

---

README.md

Basically changed `IntelliJIDEA` to `IntelliJ_IDEA` to display as `IntelliJ IDEA` (Better readability).

Add missing space to IntelliJ IDEA

---

README.md

Adds a NixOS badge to the OS section

Add NixOS OS logo

---

README.md

- There happen some conflict because of the Framework section. Although there we have Library but there is not individual section for it.

docs: update framework section name

---

README.md

Sentry is an error-detection and hazard logging software used to keep track of issues that arise during development of web applications and also provides insight as to the solution of the problem. It can also be used for performance analysis of web apps. It supports majority of the frameworks.

Sentry shield added

---

README.md

[https://img.shields.io/badge/Appian-2322F0?style=for-the-badge&logo=Appian&logoColor=white](https://img.shields.io/badge/Appian-2322F0?style=for-the-badge&logo=Appian&logoColor=white)

Add Appian

---

README.md

add dbt to ETL section
https://img.shields.io/badge/dbt-FF694B?style=for-the-badge&logo=dbt&logoColor=white

add badge for dbt

---

README.md

Added the [quarkus ](https://quarkus.io) framework.

Added Quarkus badge

---

README.md

add virtualization section
- Vagrant
- Virtualbox
- VMware
Removed vagrant from frameworks section

Virtualization section

---

README.md

Added this badge for the low-level/systems programming language <a href="https://ziglang.org">Zig</a>

add badge for zig lang

---

README.md

Added a badge for [Crowdin](https://crowdin.com/)

add badge for crowdin

---

README.md

Added a badge for Hack The Box

---

README.md

Added Keras, PyTorch, PyTorch Lightning

Added Keras, PyTorch, PyTorch Lightning

---

README.md

Gists badges ([gists-readme](https://github.com/Yizack/gists-readme)) inspired by [github-readme-stats](https://github.com/anuraghazra/github-readme-stats)

Add badges but for Gists

---

README.md

Hello, recently there is a new version available of qgis (3.28 Firenze).
Thanks
- https://www.qgis.org/es/site/forusers/download.html

Update qgis badge

---

README.md

Issue NO: [#467](https://github.com/alexandresanlim/Badges4-README.md-Profile/issues/467)
**Before**
| Badge                                                                                         | URL                                                              |
| --------------------------------------------------------------------------------------------- | ---------------------------------------------------------------- |
| <img width='200' src="https://github-readme-stats.vercel.app/api?username=alexandresanlim" /> | `https://github-readme-stats.vercel.app/api?username={username}` |
**After**
* built-in themes:  `dark`,  `radical`,  `merko`,  `gruvbox`,  `tokyonight`,  `onedark`,  `cobalt`,  `synthwave`,  `highcontrast`,  `dracula`
| Badge …

feat: customize the look of the card

---

README.md

adding the X badge to the README file

feat: add X badge in README

---

README.md

Add Whatsapp badge to socials

---

README.md

Adding CISCO badge to README.md

---

README.md

Remove duplicate SQLLite entry

---

README.md

Add bugbounty platforms

---

README.md

Add warp (terminal app)

---

README.md

Docusaurus is a react flavored static-site generator, mostly used for documentation or blog.
(Ps. Some trailing space got automatically deleted due to my IDE setting)

Added Docusaurus badge

---

README.md

feat: add biome linter

---

README.md

feat: add wezterm

---

README.md

Added SolidWorks under Design

---

README.md

Added Zod badge

---

README.md

I have added a new tool named **Chronicle** by Google Cloud in the **Software Metrics & Analytics** category.

Added a new Software Metrics & Analytics tool: Chronicle

---

README.md

Added Metasploit Tool

---

README.md

Adds TypeORM Badge (closes alexandresanlim#625)

---

README.md

Added TimescaleDB Badge

---

README.md

Added VLC Badge

---

README.md

feat: add zed

---

README.md

feat: add php yii framework logo

---

README.md

Added Vitest Badge

---

README.md

style: background changed for better readability for yii framework

---

README.md

- add education badge - 42 São Paulo
https://img.shields.io/badge/%20São%20Paulo-000000?style=for-the-badge&logo=42&logoColor=white
[![](https://img.shields.io/badge/%20São%20Paulo-000000?style=for-the-badge&logo=42&logoColor=white)](https://www.42sp.org.br/)

:sparkles: feat: add education badge - 42 São Paulo

---

README.md

(new): Added badge for DuckDB on Database section

---

README.md

adding the commitlint badge to Linters in README.md

add commitlint

---

README.md

add jetpack compose icon

---

README.md

[Immich](https://immich.app/) is the ultimate self-hosted solution for managing photos and videos locally. Designed for privacy-focused users, Immich allows you to upload, organize, and view your media effortlessly, all while keeping full control over your data. Its modern interface, API flexibility, and advanced features make it one of the best tools in the home lab ecosystem. Perfect for users looking to build a personal media hub.
Also, note that I added a new section... I didn’t find a section that fit `Immich`, so I added `HomeLab`. Home labs are growing fast, giving people more control over their data and infrastructure. This new section highlights tools for self-hosting and on-prem solutions, starting with Immich, a top-tier local media hosting platform.
Also, note, I am not an …

Add Immich

---

README.md

> [!IMPORTANT]
> The choice of colors was made based on the characteristics and purpose of each license.
> `Green:` Permissive Licenses 
> `Red:` Copyleft Licenses
> `Light Grey:` Public Domain or Creative Commons Licenses
> `Blue:` Project-Specific or Industry Licenses
> `Yellow:` Miscellaneous or Rare Licenses
> [!NOTE]  
> Font: [GitHub documentation on licensing](https://docs.github.com/pt/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#searching-github-by-license-type)

Add new section: Licenses

---

README.md

Add docker-compose

---

README.md

Added Credly badge

---

README.md

Add 42 Lisboa
